PhotoGallery/PhotoGallery/Models/PhotoViewModels/PhotoViewModel.cs
using PhotoGallery.Common.Enums;
using System;

namespace PhotoGallery.Models
{
    public class PhotoViewModel
    {
        public string PhotoId { get; set; }

        public string UniqueUserName { get; set; }

        public string PhotoName { get; set; }

        public string Description { get; set; }

        public DateTime CreationDate { get; set; }

        public DateTime UploadDate { get; set; }

        public string Place { get; set; }

        public string CameraModel { get; set; }

        public int LensFocus { get; set; }

        public DiaphragmType Diaphragm { get; set; }

        public int ShutterSpeed { get; set; }

        public string ISO { get; set; }

        public bool Flash { get; set; }

        public int Rating { get; set; }

        public byte[] MidSizeImageData { get; set; }

        public string ImageMimeType { get; set; }

        public bool IsRatedByCurrent { get; set; }
    }
}

PhotoGallery/PhotoGallery/Models/PhotoViewModels/RemovePhotoViewModel.cs
namespace PhotoGallery.Models
{
    public class RemovePhotoViewModel
    {
        public string UniqueUserName { get; set; }

        public string PhotoName { get; set; }
    }
}

PhotoGallery/PhotoGallery/Models/PhotoViewModels/UpdatePhotoViewModel.cs
using PhotoGallery.Common.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace PhotoGallery.Models
{
    public class UpdatePhotoViewModel
    {
        [Required]
        public string PhotoId { get; set; }

        [Required]
        public string UniqueUserName { get; set; }

        [Required]
        [Display(Name = "Name")]
        [MaxLength(32)]
        public string PhotoName { get; set; }

        [Required]
        [MaxLength(500)]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Creation Date")]
        public DateTime CreationDate { get; set; }

        [Required]
        [MaxLength(50)]
        public string Place { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Camera model")]
        public string CameraModel { get; set; }

        [Required]
        [Display(Name = "Lens focus")]
        public int LensFocus { get; set; }

        public DiaphragmType Diaphragm { get; set; }

        [Required]
        [Display(Name = "Shutter speed")]
        public int ShutterSpeed { get; set; }

        [MaxLength(20)]
        public string ISO { get; set; }

        [Required]
        public bool Flash { get; set; }
    }
}

PhotoGallery/PhotoGallery/Models/PhotoViewModels/UploadPhotoViewModel.cs
using PhotoGallery.Common.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace PhotoGallery.Models
{
    public class UploadPhotoViewModel
    {
        public string UniqueUserName { get; set; }

        [Required]
        [Display(Name = "Name")]
        [MaxLength(32)]
        public string PhotoName { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Creation Date")]
        public DateTime CreationDate
        {
            get
            {
                if (_internalCreationDate == new DateTime())
                    _internalCreationDate = new DateTime(1826, 1, 1);
                return _internalCreationDate;
            }
            set
            {
                _internalCreationDate = value;
            }
        }

        private DateTime _internalCreationDate;

        [Required]
        [MaxLength(50)]
        public string Place { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Camera model")]
        public string CameraModel { get; set; }

        [Required]
        [Display(Name = "Lens focus")]
        public int LensFocus { get; set; }

        [Required]
        public DiaphragmType Diaphragm { get; set; }

        [Required]
        [Display(Name = "Shutter speed")]
        public int ShutterSpeed { get; set; }

        [MaxLength(20)]
        public string ISO { get; set; }

        [Required]
        public bool Flash { get; set; }

        public DateTime UploadDate
        {
            get
            {
                return DateTime.Now;
            }
        }

        public byte[] SourceImageData { get; set; }

        public byte[] MiniatureImageData { get; set; }

        public byte[] MidSizeImageData { get; set; }

        public string ImageMimeType { get; set; }
    }
}

PhotoGallery/PhotoGallery/Controllers/PhotoController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PhotoGallery.AppCommonCore.Contracts.Services;
using PhotoGallery.AppCommonCore.Entities;
using PhotoGallery.Common;
using PhotoGallery.Common.Enums;
using PhotoGallery.Logging;
using PhotoGallery.Mapping;
using PhotoGallery.Models;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace PhotoGallery.Controllers
{
    [Authorize]
    public class PhotoController : BaseController
    {
        private IPhotoService _photoService;
        private IUserService _userService;
        private IAlbumService _albumService;

        private ICustomLogger _logger;

        public PhotoController(IPhotoService photoService, IUserService userService, IAlbumService albumService,
            ICustomLogger logger)
        {
            _photoService = photoService;
            _userService = userService;
            _albumService = albumService;

            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult ViewWall(string uniqueUserName = null, int offset = 1)
        {
            string actualUserIdOrName = uniqueUserName ?? User.Identity.GetUserId();
            Guid userId;

            if(Guid.TryParse(actualUserIdOrName,out userId))
            {
                actualUserIdOrName = _userService.GetUniqueUserNameById(userId.ToString());
            }
            else
            {
                if(!_userService.CheckIfUserExists(uniqueUserName))
                {
                    return View("Error", string.Format(Errors.UserNotFound, uniqueUserName));
                }
            }

            var request = new RequestEntity
            {
                UniqueUserName = actualUserIdOrName,
                PagingInfo = new PagingInfo
                {
                    ObjectsPerPage = ConfigurationElements.DefaultPageLimit,
                    CurrentPage = offset
                }
            };

            var response = _photoService.GetUsersWall(request);

            UsersWallViewModel result = MapperHelper.GetValue<UsersWall, UsersWallViewModel>(response);

            ViewBag.UniqueUserName = actualUserIdOrName;

            ViewBag.ResultMessage = TempData["ResultMessage"];

            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult ViewPhoto(string uniqueUserName, string photoName)
        {
            string userId = User.Identity.GetUserId();

            string currentUserName = string.Empty;

            if (!string.IsNullOrEmpty(userId))
            {
                 currentUserName = _userService.GetUniqueUserNameById(userId);
            }

            var request = new RequestEntity
            {
                UniqueUserName = uniqueUserName,
                PhotoName = photoName,
                CurrentUserName = currentUserName
            };

            var response = _photoService.GetPhoto(request);

            PhotoViewModel photo = MapperHelper.GetValue<Photo, PhotoViewModel>(response);

            if(photo==null)
            {
                var errMsg = string.Format(Errors.PhotoNotFound, photoName, uniqueUserName);
                _logger.Error(errMsg);
                return View("Error", errMsg);
            }

            ViewBag.CurrentUniqueUserName = currentUserName;

            ViewBag.ResultMessage = TempData["ResultMessage"];

            return View(photo);
        }

        [HttpGet]
        public ActionResult UploadPhoto()
        {
            if(!_userService.UserAlloweUploadPhotos(User.Identity.GetUserId()))
            {
                _logger.Error(Errors.PhotoLimitReached);
                return View("Error", Errors.PhotoLimitReached);
            }

            return View(new UploadPhotoViewModel());
        }

        [HttpPost]
        public ActionResult UploadPhoto(UploadPhotoViewModel model, HttpPostedFileBase image = null)
        {
            if(ModelState.IsValid)
            {
                if(image!=null)
                {
                    if(image.ContentLength <  ConfigurationElements.MaxFileSize * ConfigurationElements.ModifierForMaxSize)
                    {
                        model.ImageMimeType = image.ContentType;
                        if (model.ImageMimeType.ToLower().Contains("image/jpeg"))
                        {
                            string userId = User.Identity.GetUserId();

                            _logger.Info("User {0} attempts to add a new photo", userId);

                            model.UniqueUserName = _userService.GetUniqueUserNameById(userId);

                            var request = new RequestEntity
                            {
                                PhotoName = model.PhotoName,
                                UniqueUserName = model.UniqueUserName
                            };

                            if (!_photoService.CheckIfPhotoExists(request))
                            {
                                model.MiniatureImageData = new byte[image.ContentLength];

                                image.InputStream.Read(model.MiniatureImageData, 0, image.ContentLength);
                                model.MidSizeImageData = model.MiniatureImageData;
                                model.SourceImageData = model.MiniatureImageData;

                                var uploadRequest = MapperHelper.GetValue<UploadPhotoViewModel, Photo>(model);
                                _photoService.UploadPhoto(uploadRequest);

                                _logger.Info("User {0} successfully added photo", userId);
                                TempData["ResultMessage"] = string.Format(SuccessMessages.SuccessfullyUploadedPhoto, model.PhotoName);

                                return RedirectToAction("ViewPhoto", new { uniqueUserName = model.UniqueUserName, photoName = model.PhotoName });
                            }
                            else
                            {
                                ModelState.AddModelError("AlreadyExists", "Photo with such name already exists in your collection");
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("MimeType", "Wrong type, should be jpeg");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Size", "The file is too big");
                    }
                }
                else
                {
                    ModelState.AddModelError("NoPic", "There is no photo");
                }
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult RatePhoto(RequestEntity model)
        {
            if(model.CurrentUserName==model.UniqueUserName)
            {
                _logger.Error(Errors.OwnerTriesToRate);
                return null;
            }
            _photoService.Rate(model);

            model.PhotoName = model.PhotoName;

            RatingData rating=_photoService.GetRating(model);

            var response = JsonConvert.SerializeObject(rating);
            return Json(response);
        }

        [HttpPost]
        public ActionResult RemovePhoto(RemovePhotoViewModel model)
        {
            string userId = User.Identity.GetUserId();
            _logger.Info("User {0} tries to remove photo {1}", userId, model.PhotoName);

            ActionResult alternativeResult = ErrorIfNotAnOwner(model.UniqueUserName, Errors.AttemptToRemovePhoto, _userService, userId,_logger);

            if (alternativeResult == null)
            {
                alternativeResult = ErrorIfNoPhoto(model.PhotoName, model.UniqueUserName);

                if (alternativeResult == null)
                {
                    var request = new RequestEntity
                    {
                        UniqueUserName = model.UniqueUserName,
                        PhotoName = model.PhotoName
                    };

                    _photoService.RemovePhoto(request);

                    _logger.Info("Photo {0} successfully deleted", model.PhotoName);
                    TempData["ResultMessage"] = string.Format(SuccessMessages.SuccessfullyRemovedPhoto,model.PhotoName);

                    return RedirectToAction("ViewWall");
                }
            }

            return alternativeResult;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult ViewFullSize(string photoName,string uniqueUserName)
        {
            return ErrorIfNoPhoto(photoName, uniqueUserName)
                ?? View(new FullSizeViewModel
                    {
                        PhotoName=photoName,
                        UniqueUserName=uniqueUserName
                    });
        }

        [AllowAnonymous]
        public FileContentResult GetImg(string photoName,string uniqueUserName, RequiredImgSize size)
        {
            var request = new RequestEntity
            {
                RequiredSize = size,
                PhotoName = photoName,
                UniqueUserName = uniqueUserName
            };

            ImageData img = _photoService.GetImgByName(request);

            return File(img.Content, img.ImageMimeType);
        }

        [HttpGet]
        public ActionResult EditPhotoPage(string photoName,string uniqueUserName,string photoId)
        {
            return ErrorIfNotAnOwner(uniqueUserName, Errors.AttemptToEditPhoto, _userService,_logger)
                    ?? ErrorIfNoPhoto(photoName,uniqueUserName)
                    ?? View(new EditPhotoViewModel
                    {
                        PhotoName = photoName,
                        UniqueUserName = uniqueUserName
                    });
                    
        }
        
        [HttpGet]

PhotoGallery/PhotoGallery/Views/Photo/AddToAlbum.cshtml
@model AllAlbumsShortViewModel
@{
    ViewBag.Title = "AddToAlbum";
}

<h2>Add To Album</h2>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            @foreach (var album in Model.Albums)
            {
                <div class="col-md-4">
                    <strong>@album.AlbumName</strong>
                    @using (Html.BeginForm("AddToAlbum", "Photo", new AddPhotoToAlbumViewModel
                    {
                        PhotoName = ViewBag.PhotoName,
                        UniqueUserName=ViewBag.UniqueUserName,
                        AlbumName = album.AlbumName
                    }))
                    {
                        <button type="submit"><img class="img-thumbnail"
                                    src="@Html.GetImageSource(album.ImageData,album.ImageMimeType)" /></button>
                    }
                </div>
            }
        </div>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Photo/EditPhotoPage.cshtml
@model EditPhotoViewModel
@{
    ViewBag.Title = "EditPhotoPage";
}

<h2>Edit Photo</h2>

<div class="container">
    <div class="col-md-12">
        <div class="row">
            @using (Html.BeginForm("UpdatePhoto", "Photo", new { photoName = Model.PhotoName, uniqueUserName = Model.UniqueUserName }, FormMethod.Get))
            {
                <input type="submit" value="Update" class="btn btn-default col-md-4" />
            }
        </div>
        <div class="row">
            @Html.Partial("RemovePhoto", new RemovePhotoViewModel
               {
                   PhotoName = Model.PhotoName,
                   UniqueUserName = Model.UniqueUserName
               })
        </div>
        <div class="row">
            @using (Html.BeginForm("AddToAlbum", "Photo", FormMethod.Get))
            {
                <input type="hidden" name="photoName" value="@Model.PhotoName" />
                <input type="hidden" name="uniqueUserName" value="@Model.UniqueUserName" />
                <input type="submit" value="Add To Album" class="btn btn-default col-md-4" />
            }
        </div>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Photo/RemovePhoto.cshtml
@model RemovePhotoViewModel

@using (Html.BeginForm("RemovePhoto", "Photo", FormMethod.Post))
{
    @Html.HiddenFor(m => m.PhotoName);
    @Html.HiddenFor(m => m.UniqueUserName);
    <input type="submit" value="Remove" class = "btn btn-default col-md-4"/>
}

PhotoGallery/PhotoGallery/Views/Photo/UpdatePhoto.cshtml
@model UpdatePhotoViewModel

@{
    ViewBag.Title = "UpdatePhoto";
}

<h2>Update Photo</h2>


@using (Html.BeginForm("UpdatePhoto", "Photo",
                                FormMethod.Post))
{
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="panel-body">
        @Html.HiddenFor(m=>m.PhotoId)
        @Html.HiddenFor(m=>m.UniqueUserName)
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "UniqueUserName":
                case "PhotoId":
                    break;
                default:
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null,
                                new { @class = "form-control", rows = 5 })
                        }
                        else if (property.PropertyName == "Diaphragm")
                        {
                            @Html.DropDownListFor(x => x.Diaphragm, new SelectList(Enum.GetNames(typeof(DiaphragmType))));
                        }
                        else if (property.PropertyName == "Flash")
                        {
                        @Html.CheckBoxFor(x => x.Flash)
                        }
                        else if (property.PropertyName == "CreationDate")
                        {
                            @Html.EditorFor(x => x.CreationDate)
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null,
                               new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                    break;
            }
        }
    </div>
    <input type="submit" value="Update" class="btn" />
}

PhotoGallery/PhotoGallery/Views/Photo/UploadPhoto.cshtml
@model UploadPhotoViewModel
@{
    ViewBag.Title = "UploadPhoto";
}

<h2>Upload Photo</h2>
@using (Html.BeginForm("UploadPhoto", "Photo",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="panel-body">
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "SourceImageData":
                case "MiniatureImageData":
                case "MidSizeImageData":
                case "ImageMimeType":
                case "UniqueUserName":
                case "UploadDate":
                    break;
                default:
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null,
                            new { @class = "form-control", rows = 5 })
                        }
                        else if (property.PropertyName == "Diaphragm")
                        {
                            <div class="form-group">
                                @Html.DropDownListFor(x => x.Diaphragm, new SelectList(Enum.GetNames(typeof(DiaphragmType))), new { @class = "form-control" })
                            </div>
                        }
                        else if (property.PropertyName == "Flash")
                        {
                            @Html.CheckBoxFor(x=>x.Flash)
                        }
                        else if(property.PropertyName== "CreationDate")
                        {
                            <div class="form-group">
                                @Html.EditorFor(x=>x.CreationDate, new { @class = "form-control" })
                            </div>
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null,
                            new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                    break;
            }
        }
        <div class="form-group">
            <div style="position:relative;">
                <label>Image</label>
                <a class='btn' href='javascript:;'>
                    Choose File...
                    <input type="file" name="Image" size="40"
                           style="position:absolute;z-index:2;top:0;
                                    left:0,filter: alpha(opacity=0);opacity:0;
                                    background-color:transparent; color:transparent;"
                           accept="image/jpeg" id="upload-photo">
                </a>
                <script>
                    $(function () {
                        $("#upload-photo").on("change", function (e) {
                            var file = e.currentTarget.files[0];

                            var filesize = (file.size / 1024).toFixed(4);
                            if (file.name != "item" && typeof file.name != "undefined" && filesize <= 500 && file.type == "image/jpeg") {
                                $("#upload-file-info").html($(this).val());
                                return true;
                            }
                            else
                            {
                                $("#upload-file-info").html("");
                                return false;
                            }
                        })
                    });
                </script>
                <span class='label label-info' id="upload-file-info"></span>
            </div>
        </div>
    </div>
        <div class="panel-footer">
            <input type="submit" value="Upload" class="btn btn-primary" />
        </div>
}

PhotoGallery/PhotoGallery/Views/Photo/ViewFullSize.cshtml
@model FullSizeViewModel

<img src="@Url.Action("GetImg",new { photoName=Model.PhotoName, uniqueUserName = Model.UniqueUserName, size=RequiredImgSize.Source })" />

PhotoGallery/PhotoGallery/Views/Photo/ViewPhoto.cshtml
@model PhotoViewModel

@{
    ViewBag.Title = "ViewPhoto";
}

<h2>View Photo</h2>

@Html.Hidden("Rate", Model.Rating)
@Html.Hidden("IsRatedByCurrent", Model.IsRatedByCurrent)

<script>
    function onRateClick()
    {
        $.ajax({
            url: "/Photo/RatePhoto",
            type: 'POST',
            data: {"PhotoName":"@Model.PhotoName","UniqueUserName":"@Model.UniqueUserName","CurrentUserName":"@ViewBag.CurrentUniqueUserName"},
            dataType: 'json',
            success: function (data) {
                changeRate(data);
            },
            error: function(){ alert("error")}
        });
    }

    function changeRate(rating) {
        rating = JSON.parse(rating);

        var noRateClass = "glyphicon glyphicon-star-empty";
        var rateClass = "glyphicon glyphicon-star"

        $("#rating").text(rating.Rating);
        if(rating.IsRated)
        {
            $("#rateIcon").removeClass(noRateClass).addClass(rateClass);
        }
        else
        {
            $("#rateIcon").removeClass(rateClass).addClass(noRateClass);
        }
    }
</script>

<div class="container">
    @if (ViewBag.ResultMessage != null)
    {
        <div class="row">
            @ViewBag.ResultMessage
            <br />
        </div>
    }
    <div class="row">
        <div class="col-md-6 text-center">
            <div class="row">
                <a href="@Url.Action("ViewFullSize", "Photo",new { photoName=Model.PhotoName,uniqueUserName=Model.UniqueUserName })">
                    <img class="img-thumbnail" height="800"
                         src="@Html.GetImageSource(Model.MidSizeImageData,Model.ImageMimeType)" />
                </a>
            </div>
            <div class="row">
                @if (Model.UniqueUserName == ViewBag.CurrentUniqueUserName)
                {
                    @Html.ActionLink("Edit Photo Page", "EditPhotoPage",
                                 new { photoName = Model.PhotoName, uniqueUserName = Model.UniqueUserName },
                                 new { @class = "btn btn-default", @style = "color:black" })
                }
                else if(User.Identity.IsAuthenticated)
                {
                    if (Model.IsRatedByCurrent)
                    {
                        <button id="unrateBt" class="btn btn-default" onclick="onRateClick()">
                            <i id="rateIcon" class="glyphicon glyphicon-star"></i>
                        </button>
                    }
                    else
                    {
                        <button id="rateBt" class="btn btn-default" onclick="onRateClick()">
                            <i id="rateIcon" class="glyphicon glyphicon-star-empty"></i>
                        </button>
                    }
                }
            </div>
        </div>
        <div class="col-md-6">
            <p><strong>Name</strong> - @Model.PhotoName</p>
            <p><strong>About:</strong> @Model.Description</p>
            <p><strong>Created</strong> - @Model.CreationDate.ToString("MM/dd/yyyy")</p>
            <p><strong>Uploaded</strong> - @Model.UploadDate</p>
            <p><strong>Place</strong> - @Model.Place</p>
            <p><strong>Camera</strong> - @Model.CameraModel</p>
            <p><strong>Lens Focus</strong> - @Model.LensFocus</p>
            <p><strong>Shutter Speed</strong> - @Model.ShutterSpeed</p>
            <p><strong>Diaphragm</strong> - @Model.Diaphragm</p>
            <p><strong>Flash</strong> - @Html.DisplayFor(m => m.Flash)</p>
            <p><strong id="rating">@Model.Rating</strong> <span class="glyphicon glyphicon-heart"></span></p>
            @if (!string.IsNullOrEmpty(Model.ISO))
            {
                <p><strong>ISO</strong> - @Model.ISO</p>
            }
        </div>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Photo/ViewWall.cshtml
@model UsersWallViewModel
@{
    ViewBag.Title = "ViewWall";
    int startIndex = 0;
}

<div class="container">
    <div class="col-md-12">
        @if (ViewBag.ResultMessage != null)
        {
            <div class="row">
                @ViewBag.ResultMessage
            </div>
        }

        <div class="row">
            <h2>View Wall</h2>
        </div>

        @if (Model.Photos != null && Model.Photos.Count > 0)
        {
            for (; startIndex < Model.Photos.Count; startIndex += 3)
            {
                <div class="row" style="padding-bottom:10px; padding-top:10px">
                    @for (int i = 0; i < 3 && i + startIndex < Model.Photos.Count; i++)
                    {
                        <div class="col-sm-4">
                            @Html.Partial("PhotoShortSummary", Model.Photos[i + startIndex])
                        </div>
                    }
                </div>
            }
        }
        else
        {
            <h1>Alas - no photos still</h1>
        }


        <div class="row">
            <div class="col-md-12 text-center">
                @Html.PageLinks(Model.PagingInfo, x => Url.Action("ViewWall", new { uniqueUserName = ViewBag.UniqueUserName, offset = x }))
            </div>
        </div>
    </div>
</div>