PhotoGallery/PhotoGallery/Models/SearchModels/ExtendedAlbumSearchViewModel.cs
namespace PhotoGallery.Models
{
    public class ExtendedAlbumSearchViewModel
    {
        public string AlbumName { get; set; }

        public string UniqueUserName { get; set; }

        public string Description { get; set; }
    }
}

PhotoGallery/PhotoGallery/Models/SearchModels/ExtendedPhotoSearchViewModel.cs
using PhotoGallery.Common.Enums;

namespace PhotoGallery.Models
{
    public class ExtendedPhotoSearchViewModel
    {
        public string PhotoName { get; set; }

        public string UniqueUserName { get; set; }

        public string Description { get; set; }

        public string Place { get; set; }

        public string CameraModel { get; set; }

        public int? LensFocus { get; set; }

        public SearchDiaphragmType Diaphragm { get; set; }

        public int? ShutterSpeed { get; set; }

        public string ISO { get; set; }

        public bool? Flash { get; set; }

        public string FlashStub { get; set; }
    }
}

PhotoGallery/PhotoGallery/Models/SearchModels/ExtendedUserSearchViewModel.cs
namespace PhotoGallery.Models
{
    public class ExtendedUserSearchViewModel
    {
        public string Name { get; set; }

        public string UniqueUserName { get; set; }

        public string Description { get; set; }
    }
}

PhotoGallery/PhotoGallery/Models/SearchModels/SearchResultViewModel.cs
using System.Collections.Generic;

namespace PhotoGallery.Models
{
    public class SearchResultViewModel
    {
        public List<PhotoShortViewModel> Photos { get; set; }

        public List<AlbumShortViewModel> Albums { get; set; }

        public List<UserShortViewModel> Users { get; set; }
    }
}

PhotoGallery/PhotoGallery/Controllers/AlbumController.cs
using Microsoft.AspNet.Identity;
using PhotoGallery.AppCommonCore.Contracts.Services;
using PhotoGallery.AppCommonCore.Entities;
using PhotoGallery.Common;
using PhotoGallery.Logging;
using PhotoGallery.Mapping;
using PhotoGallery.Models;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace PhotoGallery.Controllers
{
    [Authorize]
    public class AlbumController : BaseController
    {
        private IAlbumService _albumService;
        private IUserService _userService;

        private ICustomLogger _logger;

        public AlbumController(IAlbumService albumService, IUserService userService, ICustomLogger customLogger)
        {
            _albumService = albumService;
            _userService = userService;

            _logger = customLogger;
        }

        [HttpGet]
        public ActionResult AddAlbum()
        {
            if (!_userService.UserAlloweUploadAlbums(User.Identity.GetUserId()))
            {
                _logger.Info(Errors.AlbumLimitReached);
                return View("Error", Errors.AlbumLimitReached );
            }

            return View(new AddAlbumViewModel());
        }

        [HttpPost]
        public ActionResult AddAlbum(AddAlbumViewModel model, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    model.ImageMimeType = image.ContentType;
                    model.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(model.ImageData, 0, image.ContentLength);

                    string userId = User.Identity.GetUserId();
                    _logger.Info("User {0} requested to add a new album", userId);

                    model.UniqueUserName = _userService.GetUniqueUserNameById(userId);

                    var album = MapperHelper.GetValue<AddAlbumViewModel, Album>(model);
                    _albumService.AddAlbum(album);

                    TempData["ResultMessage"] = string.Format(SuccessMessages.SuccessfullyCreatedAlbum, model.AlbumName);

                    return RedirectToAction("ViewAlbum", new { albumName=model.AlbumName,uniqueUserName=model.UniqueUserName });
                }
                else
                {
                    ModelState.AddModelError("NoPic", "There is no photo");
                }
            }
            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult UserAlbums(string uniqueUserName = null)
        {
            string actualUserIdOrName = uniqueUserName ?? User.Identity.GetUserId();
            Guid userId;

            if (Guid.TryParse(actualUserIdOrName, out userId))
            {
                actualUserIdOrName = _userService.GetUniqueUserNameById(userId.ToString());
            }

            var request = new RequestEntity
            {
                UniqueUserName = actualUserIdOrName
            };

            var response = _albumService.GetAllAlbumsForUser(request);

            AllAlbumsShortViewModel result = new AllAlbumsShortViewModel();
            result.Albums = MapperHelper.GetValue<List<AlbumShort>, List<AlbumShortViewModel>>(response);

            ViewBag.ResultMessage = TempData["ResultMessage"];

            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult ViewAlbum(string albumName,string uniqueUserName, int offset = 1)
        {
            var request = new RequestEntity
            {
                UniqueUserName = uniqueUserName,
                AlbumName = albumName,
                PagingInfo = new PagingInfo
                {
                    ObjectsPerPage = ConfigurationElements.DefaultPageLimit,
                    CurrentPage = offset
                }
            };

            var response = _albumService.GetAlbum(request);
            AlbumViewModel result = MapperHelper.GetValue<AlbumResult, AlbumViewModel>(response);

            string userId = User.Identity.GetUserId();
            if(!string.IsNullOrEmpty(userId))
            {
                string currentUniqueUserName = _userService.GetUniqueUserNameById(userId);

                ViewBag.CurrentUniqueUserName = currentUniqueUserName;
            }

            ViewBag.ResultMessage = TempData["ResultMessage"];

            return View(result);
        }

        [HttpGet]
        public ActionResult EditAlbum(string albumName,string uniqueUserName,string albumId)
        {
            ActionResult alternativeResult = ErrorIfNotAnOwner(uniqueUserName, Errors.AttemptToEditAlbum,_userService,_logger);

            if(alternativeResult==null)
            {
                EditAlbumViewModel model = new EditAlbumViewModel
                {
                    AlbumName = albumName,
                    UniqueUserName = uniqueUserName
                };

                return View(model);
            }

            return alternativeResult;
        }

        [HttpGet]
        public ActionResult UpdateAlbum(string albumName, string uniqueUserName)
        {
            ActionResult alternativeResult = ErrorIfNotAnOwner(uniqueUserName, Errors.AttemptToUpdateAlbum, _userService,_logger);

            if (alternativeResult == null)
            {
                var request = new RequestEntity
                {
                    AlbumName = albumName,
                    UniqueUserName = uniqueUserName
                };

                var response = _albumService.GetAlbumForUpdate(request);

                UpdateAlbumViewModel result = MapperHelper.GetValue<UpdateAlbum, UpdateAlbumViewModel>(response);
                return View(result);
            }

            return alternativeResult;
        }

        [HttpPost]
        public ActionResult UpdateAlbum(UpdateAlbumViewModel model, HttpPostedFileBase image = null)
        {
            if(ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                _logger.Info("User {0} requested to update album {1}", userId, model.AlbumId);

                ActionResult alternativeResult = ErrorIfNotAnOwner(model.UniqueUserName, Errors.AttemptToRemoveAlbum, _userService, userId, _logger);

                if (alternativeResult==null)
                {
                    if (image != null)
                    {
                        model.ImageMimeType = image.ContentType;
                        model.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(model.ImageData, 0, image.ContentLength);
                    }

                    UpdateAlbum request = MapperHelper.GetValue<UpdateAlbumViewModel, UpdateAlbum>(model);

                    _albumService.UpdateAlbum(request);

                    _logger.Info("Album {0} successfully updated", model.AlbumId);
                    TempData["ResultMessage"] = string.Format(SuccessMessages.SuccessfullyUpdatedAlbum, model.AlbumName);

                    return RedirectToAction("ViewAlbum", new { albumName = model.AlbumName, uniqueUserName = model.UniqueUserName });
                }

                return alternativeResult;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult RemoveAlbum(RemoveAlbumViewModel model)
        {
            string userId = User.Identity.GetUserId();
            _logger.Info("User {0} requested to delete album {1}", userId, model.AlbumName);

            ActionResult alternativeResult = ErrorIfNotAnOwner(model.UniqueUserName, Errors.AttemptToRemoveAlbum, _userService,userId,_logger);

            if(alternativeResult==null)
            {
                var request = new RequestEntity
                {
                    UniqueUserName = model.UniqueUserName,
                    AlbumName = model.AlbumName
                };
                _albumService.RemoveAlbum(request);

                _logger.Info("Album {0} successfully deleted", model.AlbumName);
                TempData["ResultMessage"] = string.Format(SuccessMessages.SuccessfullyRemovedAlbum, model.AlbumName);

                return RedirectToAction("UserAlbums");
            }

            return alternativeResult;
        }
    }
}

PhotoGallery/PhotoGallery/Controllers/SearchController.cs
using PhotoGallery.AppCommonCore.Contracts.Services;
using PhotoGallery.AppCommonCore.Entities;
using PhotoGallery.Common.Enums;
using PhotoGallery.Logging;
using PhotoGallery.Mapping;
using PhotoGallery.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace PhotoGallery.Controllers
{
    public class SearchController : Controller
    {
        private ISearchService _searchService;
        private ICustomLogger _logger;

        public SearchController(ISearchService searchService, ICustomLogger logger)
        {
            _searchService = searchService;

            _logger = logger;
        }

        [HttpPost]
        public ActionResult Search(string keyWord,string returnUrl)
        {
            _logger.Info("Search for keyword {0} from page {1}", keyWord, returnUrl);

            if (!string.IsNullOrEmpty(keyWord))
            {
                SearchResult response = _searchService.BasicSearch(keyWord);
                SearchResultViewModel result = MapperHelper.GetValue<SearchResult, SearchResultViewModel>(response);
                
                _logger.Info("Search for keyword {0} is succeeded with {1} results", keyWord,
                    (result.Albums.Count+result.Photos.Count+result.Users.Count).ToString());

                TempData["SearchResult"] = result;
                return RedirectToAction("SearchResult");
            }

            return Redirect(returnUrl);
        }

        [HttpGet]
        public ActionResult SearchResult()
        {
            SearchResultViewModel res = TempData["SearchResult"] as SearchResultViewModel ?? new SearchResultViewModel();
            return View(res);
        }

        [HttpGet]
        public ActionResult ExtendedPhotoSearch()
        {
            return View(new ExtendedPhotoSearchViewModel());
        }

        [HttpGet]
        public ActionResult ExtendedAlbumSearch()
        {
            return View(new ExtendedAlbumSearchViewModel());
        }

        [HttpGet]
        public ActionResult ExtendedUserSearch()
        {
            return View(new ExtendedUserSearchViewModel());
        }

        [HttpPost]
        public ActionResult ExtendedPhotoSearch(ExtendedPhotoSearchViewModel model)
        {
            bool resFlash;
            if (bool.TryParse(model.FlashStub, out resFlash))
            {
                model.Flash = resFlash;
            }
            else
            {
                model.Flash = null;
            }

            _logger.Info("Photo extended search requested");


            if (ModelState.IsValid)
            {
                var request = MapperHelper.GetValue<ExtendedPhotoSearchViewModel, ExtendedPhotoSearchRequest>(model);
                var response = _searchService.ExtendedPhotoSearch(request);

                List<PhotoShortViewModel> result = MapperHelper.GetValue<List<PhotoShort>, List<PhotoShortViewModel>>(response);

                TempData["Result"] = result;
                TempData["SearchType"] = ExtendedSearchType.Photo;

                _logger.Info("Photo extended search succeeded with {0} results",result.Count.ToString());

                return RedirectToAction("ExtendedSearchResult");
            }
            return View(model);
        }
        
        [HttpPost]
        public ActionResult ExtendedAlbumSearch(ExtendedAlbumSearchViewModel model)
        {
            _logger.Info("Album extended search requested");

            if (ModelState.IsValid)
            {
                var request = MapperHelper.GetValue<ExtendedAlbumSearchViewModel, ExtendedAlbumSearchRequest>(model);
                var response = _searchService.ExtendedAlbumSearch(request);
                List<AlbumShortViewModel> result = MapperHelper.GetValue<List<AlbumShort>, List<AlbumShortViewModel>>(response);

                TempData["Result"] = result;
                TempData["SearchType"] = ExtendedSearchType.Album;

                _logger.Info("Album extended search succeeded with {0} results", result.Count.ToString());

                return RedirectToAction("ExtendedSearchResult");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult ExtendedUserSearch(ExtendedUserSearchViewModel model)
        {
            _logger.Info("User extended search requested");

            if (ModelState.IsValid)
            {
                var request = MapperHelper.GetValue<ExtendedUserSearchViewModel, ExtendedUserSearchRequest>(model);
                var response = _searchService.ExtendedUserSearch(request);

                List<UserShortViewModel> result = MapperHelper.GetValue<List<UserShort>, List<UserShortViewModel>>(response);

                TempData["Result"] = result;
                TempData["SearchType"] = ExtendedSearchType.User;

                _logger.Info("User extended search succeeded with {0} results", result.Count.ToString());

                return RedirectToAction("ExtendedSearchResult");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult ExtendedSearchResult()
        {
            ViewBag.Result = TempData["Result"];
            ViewBag.SearchType = TempData["SearchType"];
            return View();
        }
    }
}

PhotoGallery/PhotoGallery/Views/Search/AlbumResult.cshtml
@model AlbumShortViewModel

<div class="row">
    <div class="col-md-6">
        <a href="@Url.Action("ViewAlbum", "Album",
                        new { uniqueUserName = Model.UniqueUserName, albumName = Model.AlbumName })">
            <img class="img-thumbnail" height="100"
                 src="@Html.GetImageSource(Model.ImageData, Model.ImageMimeType)" />
        </a>
        <p>Album called "@Model.AlbumName" created by @Model.UniqueUserName</p>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/ExtendedAlbumSearch.cshtml
@model ExtendedAlbumSearchViewModel
@{
    ViewBag.Title = "ExtendedAlbumSearch";
}

<h2>Extended Album Search</h2>

<div class="container">
    <div class="col-md-4">
        <div class="row">
            @using (Html.BeginForm("ExtendedAlbumSearch", "Search", FormMethod.Post))
            {
                <div class="panel-body">
                    @foreach (var property in ViewData.ModelMetadata.Properties)
                    {
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @Html.TextBox(property.PropertyName, null,
                            new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                    }
                    <input type="submit" class="btn btn-default" value="Search for album" />
                </div>
            }
        </div>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/ExtendedPhotoSearch.cshtml
@model ExtendedPhotoSearchViewModel

@{
    ViewBag.Title = "ExtendedPhotoSearch";
}

<h2>Extended Photo Search</h2>

<div class="container">
    <div class="col-md-4">
        <div class="row">
            @using (Html.BeginForm("ExtendedPhotoSearch", "Search", FormMethod.Post))
            {
                <div class="panel-body">
                    @foreach (var property in ViewData.ModelMetadata.Properties)
                    {
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        if (property.PropertyName == "Diaphragm")
                        {
                            <div class="form-group">
                                @Html.DropDownListFor(x => x.Diaphragm, new SelectList(Enum.GetNames(typeof(SearchDiaphragmType))), new { @class = "form-control" })
                            </div>
                        }
                        else if (property.PropertyName == "Flash")
                        {
                            <div class="form-group">
                                <label>@Html.RadioButton("FlashStub", "null",new { @checked=true}) Not chosen</label>
                                <label>@Html.RadioButton("FlashStub", "true") With flash</label>
                                <label>@Html.RadioButton("FlashStub", "false") Without flash</label>
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            </div>
                                }
                        @Html.ValidationMessage(property.PropertyName)
                                }
                    <input type="submit" class="btn btn-default" value="Search for photo" />
                </div>
            }
        </div>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/ExtendedSearch.cshtml
@Html.ActionLink("Extended Photo Search","ExtendedPhotoSearch","Search")
<br/>
@Html.ActionLink("Extended Album Search","ExtendedAlbumSearch","Search")
<br/>
@Html.ActionLink("Extended User Search","ExtendedUserSearch","Search")

PhotoGallery/PhotoGallery/Views/Search/ExtendedSearchResult.cshtml
@{
    ViewBag.Title = "ExtendedSearchResult";
    ExtendedSearchType type = ViewBag.SearchType;
}

<h2>Extended Search Result</h2>

<div class="container">
    <div class="col-md-6">
        @switch (type)
        {
            case ExtendedSearchType.User:
                foreach (UserShortViewModel user in ViewBag.Result)
                {
                    @Html.Partial("UserResult", user)
                }
                break;
            case ExtendedSearchType.Album:
                foreach (AlbumShortViewModel album in ViewBag.Result)
                {
                    @Html.Partial("AlbumResult", album)
                }
                break;
            case ExtendedSearchType.Photo:
                foreach (PhotoShortViewModel photo in ViewBag.Result)
                {
                    @Html.Partial("PhotoResult", photo)
                }
                break;
        }
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/ExtendedUserSearch.cshtml
@model ExtendedUserSearchViewModel
@{
    ViewBag.Title = "ExtendedUserSearch";
}

<h2>Extended User Search</h2>
<div class="container">
    <div class="col-md-4">
        <div class="row">
            @using (Html.BeginForm("ExtendedUserSearch", "Search", FormMethod.Post))
            {
                <div class="panel-body">
                    @foreach (var property in ViewData.ModelMetadata.Properties)
                    {
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @Html.TextBox(property.PropertyName, null,
                            new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                    }
                    <input type="submit" class="btn btn-default" value="Search for user" />
                </div>
            }
        </div>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/PhotoResult.cshtml
@model PhotoShortViewModel
<div class="row">
    <div class="col-md-6">
        <a href="@Url.Action("ViewPhoto", "Photo",
                            new { uniqueUserName = Model.UniqueUserName, photoName = Model.PhotoName })">
            <img class="img-thumbnail" height="100"
                 src="@Html.GetImageSource(Model.ImageData,Model.ImageMimeType)" />
        </a>
        <p>Photo called "@Model.PhotoName" created by @Model.UniqueUserName</p>
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/SearchResult.cshtml
@model SearchResultViewModel

@{
    ViewBag.Title = "SearchResult";
}

<h2>Search Results</h2>

<div class="container">
    <div class="col-md-6">
        <div class="row">
            @if (Model.Photos != null && Model.Photos.Count > 0)
            {
                <h3>Photos</h3>
                foreach (var photo in Model.Photos)
                {
                    @Html.Partial("PhotoResult",photo)
                }
            }
        </div>

        <hr />

        <div class="row">
            @if (Model.Albums != null && Model.Albums.Count > 0)
            {
                <h3>Albums</h3>
                foreach (var album in Model.Albums)
                {
                    @Html.Partial("AlbumResult",album)
                }
            }
        </div>

        <hr />

        <div class="row">
            @if (Model.Users != null && Model.Users.Count > 0)
            {
                <h3>User</h3>
                foreach (var user in Model.Users)
                {
                    @Html.Partial("UserResult",user)
                }
            }
        </div>
    </div>
    <div class="col-md-6">
        Didn't find what you've expected? Try our extended search
        <br/>
        @Html.Partial("ExtendedSearch")
    </div>
</div>

PhotoGallery/PhotoGallery/Views/Search/UserResult.cshtml
@model UserShortViewModel

<div class="row">
    <div class="col-md-12">

            <a href="@Url.Action("ViewWall", "Photo",new { uniqueUserName = Model.UniqueUserName })">
                <span class="glyphicon glyphicon-home"> @Model.Name also known as @Model.UniqueUserName</span>
            </a> 

        
    </div>
</div>